name: Execute SSH Commands

on:
  workflow_dispatch: # 手动触发工作流
  schedule:
    - cron: "0 */4 * * *"

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Get ACCOUNTS_JSON
        id: get-accounts
        run: |
          echo "$ACCOUNTS_JSON" > accounts.json
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}

      - name: Ensure script is executable
        run: chmod +x ./sshpass.sh

      - name: Generate SSH Commands
        id: generate-ssh-commands
        run: |
          echo "#!/bin/bash" > sshpass.sh
          while IFS= read -r account; do
            username=$(echo "$account" | jq -r '.username')
            password=$(echo "$account" | jq -r '.password')
            ssh=$(echo "$account" | jq -r '.ssh')

            # 直接打印输出到终端，不重定向到文件
            echo "Executing for $username@$ssh"
            echo "sshpass -p '$password' ssh -q -o StrictHostKeyChecking=no '$username@$ssh' 'bash <(curl -s https://raw.githubusercontent.com/duanxinyua/socks5-for-serv00/main/check_cron.sh)'" 
            echo "------------------------------------"
            
            # 执行 sshpass 命令并显示输出
            sshpass -p "$password" ssh -q -o StrictHostKeyChecking=no "$username@$ssh" "bash <(curl -s https://raw.githubusercontent.com/duanxinyua/socks5-for-serv00/main/check_cron.sh)"
          done < <(jq -c '.[]' accounts.json)
          chmod +x sshpass.sh

      - name: Execute SSH Commands
        run: |
          echo "Starting SSH command execution..."
          ./sshpass.sh
          echo "Finished SSH command execution."
