name: keep_serv00

on:
  schedule:
    - cron: '0 */5 * * *'  # 每 5 小时执行一次
  workflow_dispatch:  # 支持手动执行  

env:
  SERVERS_JSON: ${{ secrets.ACCOUNTS_JSON }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  
jobs:
  keep_serv00:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install jq
        run: sudo apt-get install -y jq 

      - name: Execute remote check_cron.sh script
        run: |
          curl -sSL https://raw.githubusercontent.com/duanxinyua/socks5-for-serv00/main/check_cron.sh | bash
          
