name: Run SSH Command

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次

jobs:
  run-ssh-command:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 jq
        run: sudo apt-get install -y jq

      - name: 解析 ACCOUNTS_JSON 并存入环境变量
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        run: |
          echo "$ACCOUNTS_JSON" > accounts.json
          echo "ACCOUNTS=$(jq -c . accounts.json)" >> $GITHUB_ENV

      - name: 安装 expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: 通过 SSH 连接并执行命令
        run: |
          echo "$ACCOUNTS" | jq -c '.[]' | while read -r account; do
            username=$(echo "$account" | jq -r '.username')
            password=$(echo "$account" | jq -r '.password')
            ssh_host=$(echo "$account" | jq -r '.ssh')

            echo "连接到 $ssh_host，用户 $username"

            expect <<- EOF
              set timeout 10
              spawn ssh -o StrictHostKeyChecking=no $username@$ssh_host
              expect {
                "assword:" { send -- "$password\r"; exp_continue }
                "(yes/no)?" { send -- "yes\r"; exp_continue }
                timeout { puts "SSH 连接超时"; exit 1 }
              }
              expect "$ "
              send -- "curl -s https://raw.githubusercontent.com/duanxinyua/socks5-for-serv00/main/check_cron.sh | bash\r"
              expect "$ "
              send -- "exit\r"
              expect eof
            EOF
          done
