name: Run SSH Command

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次

jobs:
  run-ssh-command:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 解析 ACCOUNTS_JSON
        id: parse-accounts
        run: echo "ACCOUNTS=$(echo '${{ secrets.ACCOUNTS_JSON }}' | jq -c .)" >> $GITHUB_ENV

      - name: 安装 expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: 通过 SSH 连接并执行命令
        env:
          ACCOUNTS: "${{ env.ACCOUNTS }}"
        run: |
          echo "$ACCOUNTS" | jq -c '.[]' | while read -r account; do
            username=$(echo "$account" | jq -r '.username')
            password=$(echo "$account" | jq -r '.password')
            ssh_host=$(echo "$account" | jq -r '.ssh')

            echo "连接到 $ssh_host，用户 $username"

            expect <<EOF
set timeout 10
spawn ssh -o StrictHostKeyChecking=no $username@$ssh_host
expect "Password:"
send -- "$password\r"
expect "$ "
send "curl -s https://raw.githubusercontent.com/duanxinyua/socks5-for-serv00/main/check_cron.sh | bash\r"
expect "$ "
send "exit\r"
expect eof
EOF
          done
