name: Execute SSH Commands

on:
  workflow_dispatch: # 手动触发工作流
  schedule:
    - cron: "0 */4 * * *"

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Get ACCOUNTS_JSON
        id: get-accounts
        run: |
          echo "$ACCOUNTS_JSON" > accounts.json
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}

      - name: Execute SSH Commands
        run: |
          while IFS= read -r account; do
            username=$(echo "$account" | jq -r '.username')
            password=$(echo "$account" | jq -r '.password')
            ssh=$(echo "$account" | jq -r '.ssh')

            echo "Executing for $username@$ssh"
            
            # 执行 sshpass 命令并检查是否被封锁
            output=$(sshpass -p "$password" ssh -o StrictHostKeyChecking=no "$username@$ssh" << 'EOF'
              bash <(curl -s https://raw.githubusercontent.com/duanxinyua/socks5-for-serv00/main/check_cron.sh)
            EOF
            )

            # 检查是否包含封锁信息
            if echo "$output" | grep -q "THE ACCOUNT HAS BEEN BLOCKED"; then
              echo "Account $username@$ssh is blocked, skipping..."
              continue  # 账户被封锁，跳过此账户
            fi

            # 如果没有被封锁，输出结果
            echo "$output"
          done < <(jq -c '.[]' accounts.json)
